module.exports.addCategory = require('./addCategory.controller')
module.exports.updateCategory = require('./updateCategory.controller')
module.exports.deleteCategory= require('./deleteCategory.controller')
module.exports.getAllCategories= require('./getAllCategories.controller')
module.exports.getCategoryById= require('./getCategoryById.controller')
