module.exports.addCategory = require('./addCategory.service')
module.exports.updateCategory = require('./updateCategory.service')
module.exports.deleteCategory= require('./deleteCategory.service')
module.exports.getAllCategories= require('./getAllCategories.service')
module.exports.getCategoryById= require('./getCategoryById.service')
